Feat: Expertise section
TheGymRwanda/zzz-unit8-maroon pull request #11
Opened 2022-11-25 12:33 UTC by ishoborabyose

###  PR DESCRIPTION

- This PR Create expertise section in the project

### TASKS COMPLETED

- [x] Insert and create in Expertise section
- [x] Modify and insert in the config file

### HOW CAN THIS PR BE TESTED

```
git clone https://github.com/TheGymRwanda/unit8-maroon
git checkout ft/expertise 
npm install
npm run dev

```

### BEFORE SUBMITTING YOUR PR, ENSURE IT HAS THE FOLLOWING

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard to understand areas
- [x] My changes generate no new warnings

### TICKET NUMBER

#012: https://www.notion.so/apeunit/Expertise-section-176d59f52faa439bb76c4417e72e18e1

2022-11-28 10:25 UTC, Delyc requested changes
Looks good, However check the design on figma  and add spaces that matches the one on design  cause looks like there is no space like on expertise text and product development

Figma:
![image](https://user-images.githubusercontent.com/90575886/204254042-ef54415f-3922-4dd8-b4f0-44aa07527350.png)


What you have:

![image](https://user-images.githubusercontent.com/90575886/204254147-68dc62f3-7cde-47c3-aedc-090ce7975ac4.png)



According to figma between expertise and the first text on the list there is a space of 24px an d between each list element there is a space of 12px vertically.

2022-11-28 16:51 UTC, Delyc submitted a review, later dismissed

2022-11-29 11:37 UTC, haroldmud approved these changes
LGTM

2022-11-29 13:52 UTC, Nkaka23dev approved these changes

2022-11-29 13:53 UTC, Nkaka23dev approved these changes

2022-11-29 13:54 UTC, Nkaka23dev approved these changes

2022-11-29 14:48 UTC, Delyc approved these changes, later dismissed

2022-11-29 15:16 UTC, Delyc approved these changes

2022-11-29 15:16 UTC, merged