Feat: Create the header component
TheGymRwanda/zzz-unit8-maroon pull request #12
Opened 2022-11-25 16:49 UTC by haroldmud

###  PR DESCRIPTION

- This PR creates the header section on all screens

### TASKS COMPLETED
- [x] Add the header content on behalf of the figma original design
- [x] Imported the Link and the Svg reusable component
- [x] Reused them to add the "arrowed Contact link 

### HOW CAN THIS PR BE TESTED

```
git clone https://github.com/TheGymRwanda/unit8-maroon
git checkout ft/header
npm install
npm run dev

```

### BEFORE SUBMITTING YOUR PR, ENSURE IT HAS THE FOLLOWING

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard to understand areas
- [x] My changes generate no new warnings

### TICKET NUMBER

#016: https://www.notion.so/apeunit/Header-section-9c90a5ed88e24e8f8c2af7d913b0e3ed

2022-11-26 17:03 UTC, ishoborabyose requested changes

2022-11-26 17:03 UTC, ishoborabyose commented on components/layout/Header.jsx
> +          <p className="hidden md:block lg:w-[61.44%]">
You should put a percentage values to config file

2022-11-28 15:58 UTC, Nkaka23dev reviewed
Look Great to me!

2022-11-28 16:07 UTC, Nkaka23dev approved these changes

2022-11-28 16:08 UTC, Nkaka23dev approved these changes

2022-11-28 16:51 UTC, Delyc approved these changes

2022-11-28 17:19 UTC, ishoborabyose approved these changes
# LGTM

2022-11-28 17:19 UTC, merged