Ft/footer component
TheGymRwanda/zzz-unit8-maroon pull request #13
Opened 2022-11-26 15:54 UTC by Nkaka23dev

###  PR DESCRIPTION

- This PR creates Footer component

### TASKS COMPLETED

- [x] Insert in Index.jsx
- [x] Update in tailwind config file
- [x] Update pages/index.js

### HOW CAN THIS PR BE TESTED

```
git clone https://github.com/TheGymRwanda/unit8-maroon
git checkout  ft/footer-component
npm install
npm run dev

```

### BEFORE SUBMITTING YOUR PR, ENSURE IT HAS THE FOLLOWING

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard to understand areas
- [x] My changes generate no new warnings

### TICKET NUMBER

#O15: https://www.notion.so/apeunit/Footer-section-bd6cfdd9284c44ff83aac82d9d246e69

2022-11-26 17:03 UTC, ishoborabyose requested changes

2022-11-26 17:03 UTC, ishoborabyose commented on components/cards/BlogCard.jsx
> +      <section className="box-border shrink-0 px-5 flex w-75.5 flex-col py-[1.375rem]  rounded-xl border border-solid border-secondaryGrey shadow-2.5xl ipad:w-112 desktop:w-29.8125 desktop:px-35 ">
You should move rem values to tailwind config file

2022-11-26 17:03 UTC, ishoborabyose commented on components/cards/BlogCard.jsx
> +       <div className="space-y-[0.75rem] py-1.1 ipad:py-2.1">
it is better to define rem values to tailwind config file

2022-11-28 16:50 UTC, Delyc approved these changes

2022-11-28 17:13 UTC, haroldmud approved these changes
You did a very good job working on this section, however there are still a tiny thing you need to improve for it to look almost perfect...

2022-11-28 17:13 UTC, haroldmud commented on components/layout/Footer.jsx
> +        </div>
Replace all the customized breakpoints by the tailwind predefined ones

2022-11-28 17:44 UTC, ishoborabyose approved these changes
# LGTM

2022-11-28 19:53 UTC, merged