Ft/about big screen
TheGymRwanda/zzz-unit8-maroon pull request #21
Opened 2022-11-29 10:35 UTC by Delyc

2022-11-29 17:21 UTC, Nkaka23dev approved these changes
This looks great!

2022-11-30 17:36 UTC, haroldmud approved these changes

2022-12-01 07:47 UTC, ishoborabyose requested changes

2022-12-01 07:47 UTC, ishoborabyose commented on components/section/Project.jsx
> +<div class="">Dacade</div>
I think you can use className instead of class. also, remember to do not left empty className.

2022-12-01 09:16 UTC, ishoborabyose approved these changes

2022-12-01 09:16 UTC, merged