Refactor/project
TheGymRwanda/zzz-unit8-maroon pull request #22
Opened 2022-11-30 07:41 UTC by Delyc

###  PR DESCRIPTION

- This PR improves project section

### TASKS COMPLETED

- [x] Displaying images and texts when hovering on a particular project

### HOW CAN THIS PR BE TESTED

```
git clone https://github.com/TheGymRwanda/unit8-maroon
git checkout ft/refactor/project
npm install
npm run dev

```

### BEFORE SUBMITTING YOUR PR, ENSURE IT HAS THE FOLLOWING

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### TICKET NUMBER

#O26: https://www.notion.so/apeunit/About-us-section-Desktop-Tablet-57355c30023c401c8263ce416b2c2efc

2022-11-30 15:18 UTC, Nkaka23dev approved these changes
Code Looks fine so far.

2022-11-30 15:26 UTC, haroldmud approved these changes

2022-11-30 15:30 UTC, haroldmud approved these changes

2022-11-30 17:23 UTC, ishoborabyose requested changes

2022-11-30 17:23 UTC, ishoborabyose commented on components/section/Project.jsx
> +    { image: "/assets/images/project-sample.png", text: "Peer-to-Peer learning platform" },
Looks good, but I think you should convert images from png to webp.

2022-11-30 17:23 UTC, ishoborabyose commented on components/section/Project.jsx
> +    { image: "/assets/images/project-sample.png", text: "Peer-to-Peer learning platform" },
I think you should convert images from png to webp.

2022-11-30 17:23 UTC, ishoborabyose commented on components/section/Project.jsx
> +    { image: "/assets/images/project-sample.png", text: "Peer-to-Peer learning platform" },
I think you should convert images from png to webp.

2022-11-30 17:23 UTC, ishoborabyose commented on components/section/Project.jsx
> +    { image: "/assets/images/project-sample.png", text: "Peer-to-Peer learning platform" },
I think you should convert images from png to webp.

2022-11-30 17:23 UTC, ishoborabyose commented on components/section/Project.jsx
> +    { image: "/assets/images/project-sample.png", text: "Peer-to-Peer learning platform" },
I think you should convert images from png to webp.

2022-11-30 17:23 UTC, ishoborabyose commented on components/section/Project.jsx
> +    { image: "/assets/images/project-sample.png", text: "Peer-to-Peer learning platform" },
I think you should convert images from png to webp.

2022-11-30 17:23 UTC, ishoborabyose commented on components/section/Project.jsx
> +    { image: "/assets/images/project-sample.png", text: "Peer-to-Peer learning platform" },
I think you should convert images from png to webp.

2022-12-01 15:14 UTC, ishoborabyose requested changes

2022-12-01 15:14 UTC, ishoborabyose commented on components/section/Project.jsx
> +  const images = [
I think you should use next image component

2022-12-01 15:19 UTC, ishoborabyose approved these changes

2022-12-01 15:20 UTC, merged